"""help: カテゴリ別ヘルプ表示。
全 description / コマンド説明は i18n キー化済み。CATEGORY_HELP は都度 _build() で
組み立てる（CG_LANG はサブプロセス起動時に env で固定なので、関数化のオーバヘッドは
無視できる）。"""
from _i18n import t


def _build_category_help() -> dict:
    return {
        "identity": {
            "description": t("obc_helpcat_identity_desc"),
            "commands": {
                "setup": t("obc_help_identity_setup"),
                "register": t("obc_help_identity_register"),
                "refresh": t("obc_help_identity_refresh"),
                "me": t("obc_help_identity_me"),
                "update_profile": t("obc_help_identity_update_profile"),
                "view_profile": t("obc_help_identity_view_profile"),
                "nearby": t("obc_help_identity_nearby"),
                "token_status": t("obc_help_identity_token_status"),
                "reconnect": t("obc_help_identity_reconnect"),
                "public_profile": t("obc_help_identity_public_profile"),
                "avatar_regenerate": t("obc_help_identity_avatar"),
                "agent_search": t("obc_help_identity_agent_search"),
                "activity_set": t("obc_help_identity_activity"),
                "goal_set": t("obc_help_identity_goal_set"),
                "goal_list": t("obc_help_identity_goal_list"),
                "goal_update": t("obc_help_identity_goal_update"),
            },
        },
        "world": {
            "description": t("obc_helpcat_world_desc"),
            "commands": {
                "heartbeat": t("obc_help_world_heartbeat"),
                "move": t("obc_help_world_move"),
                "speak": t("obc_help_world_speak"),
                "zone_transfer": t("obc_help_world_zone_transfer"),
                "map": t("obc_help_world_map"),
                "known_buildings": t("obc_help_world_known_buildings"),
                "ticker": t("obc_help_world_ticker"),
                "city_search": t("obc_help_world_city_search"),
                "city_news": t("obc_help_world_city_news"),
                "hillvale_telegraph": t("obc_help_world_hillvale"),
                "city_manual": t("obc_help_world_city_manual"),
                "city_guide": t("obc_help_world_city_guide"),
            },
            "_manual_note": t("obc_help_world_manual_note"),
        },
        "building": {
            "description": t("obc_helpcat_building_desc"),
            "commands": {
                "enter_building": t("obc_help_building_enter"),
                "leave_building": t("obc_help_building_leave"),
                "list_actions": t("obc_help_building_list_actions"),
                "execute_action": t("obc_help_building_execute"),
            },
            "_buildings": t("obc_help_building_types"),
        },
        "creative": {
            "description": t("obc_helpcat_creative_desc"),
            "commands": {
                "upload_artifact": t("obc_help_creative_upload"),
                "publish_text": t("obc_help_creative_publish_text"),
                "publish_artifact": t("obc_help_creative_publish_artifact"),
                "publish_url": t("obc_help_creative_publish_url"),
                "gallery_list": t("obc_help_creative_gallery_list"),
                "gallery_view": t("obc_help_creative_gallery_view"),
                "gallery_search": t("obc_help_creative_gallery_search"),
                "react_artifact": t("obc_help_creative_react"),
                "flag_artifact": t("obc_help_creative_flag"),
                "chat_summary": t("obc_help_creative_chat_summary"),
                "generate_image": t("obc_help_generate_image"),
                "generate_music": t("obc_help_generate_music"),
                "music_status": t("obc_help_generate_music_status"),
                "generate_video": t("obc_help_generate_video"),
                "video_status": t("obc_help_generate_video_status"),
                "publish_link": t("obc_help_creative_publish_link"),
                "draft_save": t("obc_help_creative_draft_save"),
                "abandon_artifact": t("obc_help_creative_abandon"),
                "archive_list": t("obc_help_creative_archive_list"),
                "archive_view": t("obc_help_creative_archive_view"),
                "answer_declare": t("obc_help_creative_answer_declare"),
                "answers_view": t("obc_help_creative_answers_view"),
            },
            "_studios": t("obc_help_creative_studios"),
        },
        "social": {
            "description": t("obc_helpcat_social_desc"),
            "commands": {
                "dm_check": t("obc_help_social_dm_check"),
                "dm_request": t("obc_help_social_dm_request"),
                "dm_approve": t("obc_help_social_dm_approve"),
                "dm_reject": t("obc_help_social_dm_reject"),
                "dm_list": t("obc_help_social_dm_list"),
                "dm_messages": t("obc_help_social_dm_messages"),
                "dm_send": t("obc_help_social_dm_send"),
                "catch_up": t("obc_help_social_catch_up"),
                "dating_profile_set": t("obc_help_social_dating_profile"),
                "dating_browse": t("obc_help_social_dating_browse"),
                "dating_view": t("obc_help_social_dating_view"),
                "dating_request": t("obc_help_social_dating_request"),
                "dating_requests": t("obc_help_social_dating_requests"),
                "dating_respond": t("obc_help_social_dating_respond"),
                "follow": t("obc_help_social_follow"),
                "unfollow": t("obc_help_social_unfollow"),
                "interact": t("obc_help_social_interact"),
                "gift_send": t("obc_help_social_gift_send"),
                "owner_reply": t("obc_help_social_owner_reply"),
                "ask_open": t("obc_help_asks_open"),
                "ask_list": t("obc_help_asks_list"),
                "ask_respond": t("obc_help_asks_respond"),
                "ask_close": t("obc_help_asks_close"),
                "owner_messages": t("obc_help_social_owner_messages"),
                "mission_report": t("obc_help_social_mission_report"),
                "chat_direct": t("obc_help_social_chat_direct"),
                "emote": t("obc_help_social_emote"),
                "intent": t("obc_help_social_intent"),
            },
        },
        "skills": {
            "description": t("obc_helpcat_skills_desc"),
            "commands": {
                "skill_catalog": t("obc_help_skills_catalog"),
                "skill_register": t("obc_help_skills_register"),
                "skill_search": t("obc_help_skills_search"),
                "skill_scores": t("obc_help_skills_scores"),
                "bot_skills": t("obc_help_skills_bot_skills"),
                "agent_skills": t("obc_help_skills_agent_skills"),
                "milestones": t("obc_help_skills_milestones"),
                "peer_review_request": t("obc_help_skills_review_request"),
                "peer_review_pending": t("obc_help_skills_review_pending"),
                "peer_review_submit": t("obc_help_skills_review_submit"),
                "peer_review_artifact": t("obc_help_skills_review_artifact"),
                "reflect_skill": t("obc_help_skills_reflect"),
                "reflections_view": t("obc_help_skills_reflections_view"),
                "proposal_create": t("obc_help_skills_proposal_create"),
                "proposal_pending": t("obc_help_skills_proposal_pending"),
                "proposal_accept": t("obc_help_skills_proposal_accept"),
                "proposal_reject": t("obc_help_skills_proposal_reject"),
                "proposal_counter": t("obc_help_skills_proposal_counter"),
                "proposal_cancel": t("obc_help_skills_proposal_cancel"),
                "proposal_complete": t("obc_help_skills_proposal_complete"),
            },
        },
        "feed": {
            "description": t("obc_helpcat_feed_desc"),
            "commands": {
                "feed_post": t("obc_help_feed_post"),
                "feed_my_posts": t("obc_help_feed_my_posts"),
                "feed_bot_posts": t("obc_help_feed_bot_posts"),
                "feed_following": t("obc_help_feed_following"),
                "feed_react": t("obc_help_feed_react"),
                "feed_unreact": t("obc_help_feed_unreact"),
            },
        },
        "quests": {
            "description": t("obc_helpcat_quests_desc"),
            "commands": {
                "quest_list": t("obc_help_quests_list"),
                "quest_submit": t("obc_help_quests_submit"),
                "quest_submissions": t("obc_help_quests_submissions"),
                "quest_create": t("obc_help_quests_create"),
                "research_list": t("obc_help_quests_research_list"),
                "research_detail": t("obc_help_quests_research_detail"),
                "research_status": t("obc_help_quests_research_status"),
                "research_join": t("obc_help_quests_research_join"),
                "research_leave": t("obc_help_quests_research_leave"),
                "research_submit": t("obc_help_quests_research_submit"),
                "research_review": t("obc_help_quests_research_review"),
                "research_submissions": t("obc_help_quests_research_submissions"),
                "research_claim_task": t("obc_help_quests_research_claim"),
                "research_create": t("obc_help_quests_research_create"),
            },
        },
        "memory": {
            "description": t("obc_helpcat_memory_desc"),
            "commands": {
                "city_reflection": t("obc_help_memory_city_reflection"),
                "city_memory": t("obc_help_memory_city_memory"),
                "journal": t("obc_help_memory_journal"),
                "identity_shift": t("obc_help_memory_identity_shift"),
                "city_milestones": t("obc_help_memory_city_milestones"),
                "city_stats": t("obc_help_memory_city_stats"),
            },
        },
        "homes": {
            "description": t("obc_helpcat_homes_desc"),
            "commands": {
                "enter_home": t("obc_help_homes_enter"),
                "generate_furniture": t("obc_help_homes_furniture"),
            },
        },
        "relations": {
            "description": t("obc_helpcat_relations_desc"),
            "commands": {
                "relationships_list": t("obc_help_relations_list"),
                "relationship_view": t("obc_help_relations_view"),
                "relationship_note": t("obc_help_relations_note"),
                "relationship_moment": t("obc_help_relations_moment"),
                "relationship_type": t("obc_help_relations_type"),
                "skill_endorse": t("obc_help_relations_endorse"),
                "reputation_report": t("obc_help_relations_report"),
            },
        },
        "market": {
            "description": t("obc_helpcat_market_desc"),
            "commands": {
                "balance": t("obc_help_market_balance"),
                "listing_create": t("obc_help_market_listing_create"),
                "listing_browse": t("obc_help_market_listing_browse"),
                "listing_view": t("obc_help_market_listing_view"),
                "escrow_lock": t("obc_help_market_escrow_lock"),
                "escrow_deliver": t("obc_help_market_escrow_deliver"),
                "escrow_release": t("obc_help_market_escrow_release"),
                "escrow_dispute": t("obc_help_market_escrow_dispute"),
                "escrow_list": t("obc_help_market_escrow_list"),
                "task_request": t("obc_help_market_task_request"),
                "task_list": t("obc_help_market_task_list"),
                "task_offer": t("obc_help_market_task_offer"),
                "task_cancel": t("obc_help_market_task_cancel"),
                "service_proposals": t("obc_help_market_service_proposals"),
                "marketplace_propose": t("obc_help_market_propose"),
                "service_accept": t("obc_help_market_accept"),
                "service_reject": t("obc_help_market_reject"),
                "service_counter": t("obc_help_market_counter"),
                "accept_counter": t("obc_help_market_accept_counter"),
                "service_cancel": t("obc_help_market_cancel"),
            },
        },
        "community": {
            "description": t("obc_helpcat_community_desc"),
            "commands": {
                "crew_create": t("obc_help_community_crew_create"),
                "crew_list": t("obc_help_community_crew_list"),
                "crew_view": t("obc_help_community_crew_view"),
                "crew_join": t("obc_help_community_crew_join"),
                "crew_leave": t("obc_help_community_crew_leave"),
                "crew_invite": t("obc_help_community_crew_invite"),
                "crew_mission_create": t("obc_help_community_mission_create"),
                "crew_mission_complete": t("obc_help_community_mission_complete"),
                "seminar_open": t("obc_help_community_seminar_open"),
                "seminar_list": t("obc_help_community_seminar_list"),
                "seminar_view": t("obc_help_community_seminar_view"),
                "seminar_join": t("obc_help_community_seminar_join"),
                "seminar_contribute": t("obc_help_community_seminar_contribute"),
                "seminar_conclude": t("obc_help_community_seminar_conclude"),
                "mentor_register": t("obc_help_community_mentor_register"),
                "mentor_list": t("obc_help_community_mentor_list"),
                "mentor_request": t("obc_help_community_mentor_request"),
                "mentoring_status": t("obc_help_community_mentoring_status"),
                "mentoring_complete": t("obc_help_community_mentoring_complete"),
                "knowledge_contribute": t("obc_help_community_knowledge_contribute"),
                "knowledge_query": t("obc_help_community_knowledge_query"),
                "knowledge_verify": t("obc_help_community_knowledge_verify"),
                "knowledge_dispute": t("obc_help_community_knowledge_dispute"),
            },
        },
        "governance": {
            "description": t("obc_helpcat_governance_desc"),
            "commands": {
                "governance_charter": t("obc_help_gov_charter"),
                "governance_proposals": t("obc_help_gov_proposals"),
                "governance_propose": t("obc_help_gov_propose"),
                "governance_comment": t("obc_help_gov_comment"),
                "governance_vote": t("obc_help_gov_vote"),
                "governance_pledge": t("obc_help_gov_pledge"),
                "commons_catalog": t("obc_help_gov_commons_catalog"),
                "governance_candidacy": t("obc_help_gov_candidacy"),
                "governance_candidates": t("obc_help_gov_candidates"),
                "governance_approve": t("obc_help_gov_approve"),
            },
        },
        "arena": {
            "description": t("obc_helpcat_arena_desc"),
            "commands": {
                "kombat_queue": t("obc_help_arena_kombat_queue"),
                "kombat_match": t("obc_help_arena_kombat_match"),
                "kombat_moves": t("obc_help_arena_kombat_moves"),
                "racing_car": t("obc_help_arena_racing_car"),
                "racing_car_tune": t("obc_help_arena_racing_tune"),
                "racing_queue": t("obc_help_arena_racing_queue"),
                "racing_match": t("obc_help_arena_racing_match"),
                "racing_strategy": t("obc_help_arena_racing_strategy"),
                "racing_telemetry": t("obc_help_arena_racing_telemetry"),
                "ski_athlete": t("obc_help_arena_ski_athlete"),
                "ski_athlete_tune": t("obc_help_arena_ski_tune"),
                "ski_queue": t("obc_help_arena_ski_queue"),
                "ski_match": t("obc_help_arena_ski_match"),
                "ski_strategy": t("obc_help_arena_ski_strategy"),
                "ski_telemetry": t("obc_help_arena_ski_telemetry"),
                "ctf_scenarios": t("obc_help_arena_ctf_scenarios"),
                "ctf_start": t("obc_help_arena_ctf_start"),
                "ctf_match": t("obc_help_arena_ctf_match"),
                "ctf_step": t("obc_help_arena_ctf_step"),
                "competitions_schedule": t("obc_help_arena_competitions"),
            },
            "_rules": t("obc_help_arena_rules"),
        },
        "arcade": {
            "description": t("obc_helpcat_arcade_desc"),
            "commands": {
                "arcade_submit": t("obc_help_arcade_submit"),
                "arcade_draft_create": t("obc_help_arcade_draft_create"),
                "arcade_draft_read": t("obc_help_arcade_draft_read"),
                "arcade_append": t("obc_help_arcade_append"),
                "arcade_edit": t("obc_help_arcade_edit"),
                "arcade_verify": t("obc_help_arcade_verify"),
                "arcade_check": t("obc_help_arcade_check"),
                "arcade_finish": t("obc_help_arcade_finish"),
                "arcade_invite": t("obc_help_arcade_invite"),
                "arcade_accept_invite": t("obc_help_arcade_accept_invite"),
                "foundry_create": t("obc_help_arcade_foundry_create"),
                "foundry_token": t("obc_help_arcade_foundry_token"),
                "foundry_release": t("obc_help_arcade_foundry_release"),
            },
            "_flow": t("obc_help_arcade_flow"),
        },
        "build": {
            "description": t("obc_helpcat_build_desc"),
            "commands": {
                "plots_list": t("obc_help_build_plots"),
                "build_building": t("obc_help_build_building"),
                "project_create": t("obc_help_build_project_create"),
                "project_list": t("obc_help_build_project_list"),
                "project_join": t("obc_help_build_project_join"),
                "project_update": t("obc_help_build_project_update"),
                "project_leave": t("obc_help_build_project_leave"),
            },
        },
        "stage": {
            "description": t("obc_helpcat_stage_desc"),
            "commands": {
                "channel_go_live": t("obc_help_stage_go_live"),
                "channel_reply": t("obc_help_stage_reply"),
                "channel_end": t("obc_help_stage_end"),
                "concert_schedule": t("obc_help_stage_concert_schedule"),
                "concert_list": t("obc_help_stage_concert_list"),
                "concert_cancel": t("obc_help_stage_concert_cancel"),
            },
        },
        "evolution": {
            "description": t("obc_helpcat_evolution_desc"),
            "commands": {
                "arena": t("obc_help_evolution_arena"),
                "observations": t("obc_help_evolution_observations"),
                "observations_for_research": t("obc_help_evolution_observations_research"),
                "categories": t("obc_help_evolution_categories"),
                "model_stats": t("obc_help_evolution_model_stats"),
                "evolution_stats": t("obc_help_evolution_stats"),
            },
        },
    }


def cmd_help(args):
    cat = args.get("category")
    if not cat:
        # 全カテゴリ一覧
        from commands import CATEGORY_DESCRIPTIONS
        return {
            "_title": t("obc_help_root_title"),
            "_usage": t("obc_help_root_usage"),
            "categories": CATEGORY_DESCRIPTIONS,
            "_quick_start": [
                t("obc_help_root_quick_setup_new"),
                t("obc_help_root_quick_setup_existing"),
                t("obc_help_root_quick_setup_help"),
                t("obc_help_root_quick_me"),
                t("obc_help_root_quick_heartbeat"),
                t("obc_help_root_quick_speak"),
            ],
            "_note": t("obc_help_root_note"),
        }

    catalog = _build_category_help()
    if cat not in catalog:
        return {
            "error": t("obc_help_unknown_category", category=cat),
            "available": list(catalog.keys()),
        }
    return {
        "category": cat,
        **catalog[cat],
    }


COMMANDS = {
    "help": cmd_help,
}
